### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by beingcoder29**

### CODE REVIEW

**Comment by oliverklee** [comment]
This looks like one of these hacktoberfest dummy PRs. Closing.

@beingcoder29, if you provide PRs that actually improve things, those are more than welcome.

**Comment by beingcoder29** [comment]
PR means?

**Comment by oliverklee** [comment]
PR = pull request

I also recommend to read a [Markdown guide](https://www.markdownguide.org/getting-started/) - in most Markdown documents, you do not need "real" HTML.

**Comment by oliverklee** [comment]
@beingcoder29 And here's an introduction to the Markdown syntax: https://opensource.com/article/19/9/introduction-markdown

**Comment by beingcoder29** [comment]
Pls don't reject pull request before 7 days

**Comment by oliverklee** [comment]
I will reject PRs as soon as I have time. If you want that t-shirt, I recommend you create pull requests that add something real instead of dummy changes.

**Comment by beingcoder29** [comment]
I am a java guy what type of chage you need
?

**Comment by oliverklee** [comment]
@beingcoder29 Both for https://github.com/oliverklee/phpparser and https://github.com/oliverklee/pixy, these kinds of changes will be helpful:

- most important: fix the Travis CI builds (if there are multiple changes needed, one change per PR would be most helpful)
- update to newer versions of the JDK
- read the docs (e.g., the README), follow the steps, and fill in any blank or fix anything that is incorrect

For Pixy, there also a list of open issues that might be a bit more advanced: https://github.com/oliverklee/pixy/issues

**Pull request closed without merging**
